const raposa = {
    'id': 'raposa',
    'nome': 'Raposa-vermelha',
    'peso': 10,
    'idade': 5,
    'texto2': 'As raposas vermelhas (Vulpes vulpes) são mamíferos, carnívoros, pertencente à família Canidae. Este animal é uma das várias espécies do gênero Vulpes, gênero ao qual pertencem a maioria das espécies de raposa, embora algumas espécies pertençam a outros gêneros.',
    'texto3': 'A raposa vermelha, como evidencia o nome, tem a pelagem vermelho-amarelada. Chega a medir 1m de comprimento, fora seu rabo que é espesso e longo (mede de 32 a 49cm), que geralmente tem a ponta branca. Alcança 40cm de altura, e pode pesar até 10 kg. Suas orelhas são grandes, mais escuras que o tom de sua pelagem por fora, e brancas por dentro. Os sentidos das raposas são muito apurados.',
    'texto4': 'As raposas vermelhas são animais de hábitos crepusculares e noturnos. Alimentam-se preferencialmente de pequenos roedores, ovos e filhotes de aves, coelhos e eventualmente torna-se necrófaga, ou seja, alimenta-se de carne em decomposição. Frutas e grãos compõem sua alimentação no outono.',
    'texto5': 'Algumas pessoas são como raposas pois são imprecisas e inconsistentes, outras são como porcos-espinhos pois focam o essencial, ignoram o resto e são eficazes.“ —  James C. Collins 1958',
    'texto6': 'Esses animais são encontrados em toda a Europa (inclusive na Grã-Bretanha), Ásia, Oriente Médio, norte da África, Austrália e na América do Norte. Vive, portanto, em hábitats diversos, geralmente em tocas, evitando apenas os desertos e as florestas muito densas.',
    'texto7': 'Estima-se que existam aproximadamente 48 subespécies de raposas vermelhas, porém essa informação não foi comprovada cientificamente. As raposas vermelhas vivem até 12 anos em seu habitat natural, sobretudo em regiões em que a caça não é permitida. Em cativeiro chegam a viver até 15 anos.',
    'caracteristicas': ['Surgiu: 200 anos', 'Tipo: Mamífero', 'Idade Média: 4 anos', 'Macho adulto: 4.2-9 kg', 'Fêmea adulta: 3.7-8kg', 'Família: Canídeos']
}
const koala = {
    'id': 'koala',
    'nome': 'Coala',
    'peso': 13,
    'idade': 15,
    'texto2': 'Os coalas são animais australianos, pertencentes ao grupo dos mamíferos marsupiais, isto é, possuem uma bolsa ventral, chamada de bolsa marsupial ou marsúpio, para o desenvolvimento dos filhotes que nascem prematuros, assim como acontece com os cangurus da mesma região e os gambás que podem ser vistos no Brasil. Na Austrália, os coalas podem ser encontrados na região de florestas a nordeste e sudeste do país.',
    'texto3': 'Os coalas são animais lentos que raramente descem das árvores e bebem pouca água, recorrendo ao líquido apenas em caso de doenças ou extrema desidratação devido ao calor. Geralmente, conseguem todo o líquido que necessitam através da alimentação que consiste basicamente em folhas de algumas espécies de eucalipto. As folhas são cuidadosamente escolhidas, e frequentemente as mais novas são recolhidas. Após ingeri-las as folhas permanecem em suas bochechas para serem mastigadas aos poucos e a absorção do nutriente acontece em seu longo intestino.',
    'texto4': 'As principais características desse animal são: a cabeça grande, o focinho curto e os olhos bem separados. O nariz achatado com as narinas em forma de V tem papel importante no equilíbrio térmico do corpo. O pelo do animal é denso e macio desempenhando importante função na proteção contra os fatores meteorológicos e regulação térmica. Como eles não constroem abrigos, ficam constantemente expostos a chuvas e o Sol. A pelagem no dorso dos coalas é bastante densa e ficam mais escurecidas durante o inverno para captar mais o calor do Sol e durante o verão tornam-se mais escassas para não aquecer o corpo do animal.',
    'texto5': 'Sou como um coala. Gosto de estar desacompanhada. Gosto de ser solitária. Gosto de ser eu',
    'texto6': 'Os coalas possuem poucos predadores, prevalecendo o homem que os caçam pela pelagem e os aborígenes para se alimentar preferindo o coala por serem lentos e quando ameaçados não fugirem. No ambiente natural o cachorro selvagem (Canis dingo) se alimenta dos coalas velhos ou doentes, já que os jovens e de boa saúde podem machucar o cachorro com facilidade com suas garras.',
    'texto7': 'A principal ameaça sofrida pelos coalas são a caça desses animais para retirar sua pele e vendê-la a indústrias têxteis que fabricam casacos com esses animais. Além disso, o desmatamento que diminui a área alimentícia e as queimadas que além de destruir as árvores ainda matam inúmeros animais que não conseguem fugir a tempo devido ao seu deslocamento ser lento.',
    'caracteristicas': ['Surgiu: 230 anos', 'Tipo: Mamífero', 'Idade Média: 15 anos', 'Macho adulto: 4-9 kg', 'Fêmea adulta: 4-7kg', 'Família: Phascolarctidae']
}
const tucano = {
    'id': 'tucano',
    'nome': 'Tucano',
    'peso': 0.6,
    'idade': 40,
    'texto2': 'Os tucanos são aquelas espécies de aves pertencentes à Ordem Piciforme, Família Ramphastida, composta por cerca de 30 espécies encontradas principalmente no Brasil, México e Argentina. Essa ordem aviária é caracterizada por apresentar pés zigomáticos (nos quais a 2ª e 3ª falange são voltadas para frente e a 1ª e 4ª falange são voltadas para trás) e glândula uropigial (secreta o óleo utilizado na impermeabilização das penas) bipartida. Além dessas características, os ranfastídeos apresentam ainda ausência de inglúvio (papo) e presença de um bico córneo pneumático que é bem leve e resistente. O bico participa também da dispersão de calor, por ser muito vascularizado. São aves sem hábitos migratórios, arborícolas, que vivem em bando e se alimentam principalmente de frutas, complementando a dieta com alguns insetos e pequenas presas.',
    'texto3': 'Os tucanos podem chegar a 60 centímetros de comprimento. Eles possuem asas curtas e arredondadas, bem como uma longa cauda, porém sua característica principal é o enorme bico, que em algumas espécies pode medir até 22 centímetros. O tucano consegue voar porque, apesar do tamanho, esse bico não é pesado, pois é feito de osso leve coberto de queratina (o mesmo material de que são feitas as unhas humanas).',
    'texto4': 'Em muitos tucanos, o bico tem tons de verde, vermelho, branco ou amarelo. Essas cores ajudam a distinguir uma espécie da outra. No Brasil, as espécies mais populares são o tucano-toco, de bico amarelo, e seus parentes tucano-de-bico-preto e tucano-de-bico-verde. O tucano-toco é o maior deles, chegando a pesar cerca de 500 gramas.',
    'texto5': 'Tucano colorido como o o crepúsculo, tão lindo quanto',
    'texto6': 'Os tucanos formam ninhos no alto do tronco de árvores, acomodando-se em buracos naturais ou em ninhos de pica-pau abandonados. Cada fêmea bota de dois a quatro ovos, que eclodem após cerca de dezoito dias. Os filhotes nascem de olhos fechados, sem plumagem nenhuma e com um bico largo, porém curto. Os pais cuidam da cria durante cerca de 45 dias, até que os filhotes estejam prontos para voar. Famílias de tucanos podem continuar juntas mesmo após esse período.',
    'texto7': 'Os tucanos alimentam-se principalmente de frutas, mas também podem comer insetos, cobras, rãs e lagartos. Muitas vezes eles invadem os ninhos de pássaros canoros e comem seus ovos ou até mesmo seus filhotes. Para se alimentar, o tucano pega a comida com a ponta do bico e joga a cabeça para trás, mandando o alimento para a garganta. As bordas serrilhadas do bico ajudam a quebrar frutas grandes em pedaços menores.',
    'caracteristicas': ['Surgiu: 280 anos', 'Tipo: Aves', 'Idade Média: 40 anos', 'Macho adulto: 600g', 'Fêmea adulta: 540g', 'Família: Ramphastidae']
}
const tartaruga = {
    'id': 'tartaruga',
    'nome': 'Tartaruga',
    'peso': '160',
    'idade': '150',
    'texto2': 'As tartarugas marinhas são da Ordem Testudines e estão agrupadas nas famílias Dermochelydae (Dermochelys coriacea) e Cheloniidae (Caretta caretta, Chelonia mydas, Eretmochelys imbricata, Lepidochelys olivacea, Lepidochelys kempii e Natator depressus) constituindo ao todo seis gêneros e sete espécies. São répteis existentes há mais de 180 milhões de anos e teriam evoluído a partir das tartarugas de água doce. A carapaça das tartarugas marinhas é mais achatada, o que as deixam mais leves e hidrodinâmicas. Possuem visão, olfato e audição desenvolvidos e as patas são eficientes nadadeiras debaixo d´água. Outra importante adaptação foi o surgimento de glândulas de sal, localizadas próximo aos olhos. A maioria das espécies de tartarugas marinhas é migratória e se orientam pelo oceano com a ajuda do campo magnético terrestre.',
    'texto3': 'São répteis pulmonados com grande capacidade de permanência debaixo d’água, quer em repouso, quer em busca de alimento. Tal capacidade resulta da eficiente distribuição do oxigênio pelo corpo, somada ao baixo nível metabólico e um pequeno auxílio da respiração acessória, possibilitada pela troca de gases em órgãos como a cloaca e a faringe. A dieta é onívora sendo constituída por zooplâncton, celenterados, salpas, algas, moluscos, peixes e crustáceos.',
    'texto4': 'A maior parte das ocorrências reprodutivas está concentrada nas regiões tropicais e subtropicais. No Brasil, a temporada de desovas, de forma geral, vai de setembro a abril nas praias do continente e de dezembro a junho nas ilhas oceânicas. Uma mesma fêmea pode fazer mais de uma desova em uma mesma temporada e os ciclos reprodutivos podem ser anuais, bienais, trienais ou irregulares. A temperatura ambiente é um fator muito importante no ciclo de vida das tartarugas marinhas, influenciando diretamente a determinação do sexo, nascimento e crescimento dos filhotes, a atividade no interior do ninho, o tempo de incubação dos ovos, a hibernação e a distribuição geográfica, entre outros fatores.',
    'texto5': 'O tempo pode correr como uma lebre, mas os sentimentos andam como tartarugas, e todos os dias eu fico na esperança que a lebre pare pra descansar pra tartaruga superar a lebre.',
    'texto6': 'No Brasil, ocorrem cinco espécies de tartarugas marinhas: Caretta caretta (conhecida como tartaruga cabeçuda), Chelonia mydas (tartaruga verde), Eretmochelys imbricata (tartaruga de pente), Dermochelys coriácea (tartaruga de couro) e Lepidochelys olivacea (tartaruga de oliva).',
    'texto7': 'Atualmente, todas as espécies de tartarugas marinhas estão incluídas nas listas de espécies ameaçadas de extinção. As principais ameaças às tartarugas marinhas são o impacto do desenvolvimento costeiro acelerado, a captura incidental por redes de pesca, a caça para consumo humano da carne e da gordura das tartarugas, as mudanças climáticas, a poluição e os patógenos. Na década de 80, no Brasil, foi criado o Projeto Tartaruga marinha que, hoje, é conhecido como o Projeto TAMAR. Este projeto tem como missão a pesquisa, conservação e o manejo das cinco espécies de tartarugas marinhas que ocorrem no país e atualmente é visto como referência na conservação nacional das tartarugas marinhas, protegendo cerca de 1.100 km de praias, em 25 localidades em áreas de alimentação, desova, crescimento e descanso desses animais, no litoral e ilhas oceânicas, em nove estados brasileiros. O projeto também realiza ações permanentes de educação ambiental para turistas, moradores, pescadores e empresários sobre a importância da preservação do ciclo de vida das tartarugas marinhas.',
    'caracteristicas': ['Surgiu: 200 milhões de anos', 'Tipo: Reptilia', 'Idade Média: 150', 'Macho adulto: 160kg', 'Fêmea adulta: 140kg', 'Família: Cheloniidae']
}



                